### ISSUE TITLE
Figure Legend Cutoff in Plots

### ISSUE THREAD

**Issue by jvelghe** [SGDDNB/ShinyCell#10]
Hi, once again this is an awesome package! 

My legends in some of the plots get cut off in the viewing window of the shiny app, as well as in the images I download. I'm not the most experienced ggplot user, but I don't think font size is the issue, as there are 11 items in this legend. Would you be able to point me to where in the source code I could go to maybe change this and have it as maximum 5 items per line in the legend?

Thank you!

![hisletUMAP1_UMAP2_Cell Type](https://user-images.githubusercontent.com/62624873/116013261-14802100-a5e4-11eb-9a51-44a24408b9f1.png)

<img width="698" alt="Screen Shot 2021-04-25 at 4 32 03 PM" src="https://user-images.githubusercontent.com/62624873/116013219-c79c4a80-a5e3-11eb-97ef-10ce6e6fccdd.png">

**Comment by jvelghe** [comment]
Resolved!

**Comment by jfouyang** [comment]
Hey, glad that you resolved the problem on your own. In case anyone refers to this issue, I will provide a solution here.

When creating the ShinyCell config using the command `createConfig`, one can specify the argument `legendCols = 4`, which specifies a maximum of 4 columns when displaying the legend. We chose to limit the number of columns (as opposed to rows) as that affects how "wide" the legends are.

**Comment by jvelghe** [comment]
Thanks John! Yes, I can't believe that didn't occur to me until then. 

You're doing a great job maintaining and supporting this awesome package by the way!

-Jane
