### ISSUE TITLE
Error in Match

### ISSUE THREAD

**Issue by CynAro** [SGDDNB/ShinyCell#13]
Hi, I am trying to use ShinyCell with h5ad file as input. The code is able to read the h5ad file but brought up this warning. 
__Moving element from .uns['neighbors']['distances'] to .obsp['distances'].
This is where adjacency matrices should go now._

When I try to make the Shiny App however, I get the following error
_Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments_

**Comment by CynAro** [comment]
I should mention that I got the same error in match when trying to run the example file-endocrinogenesis_day15.h5ad.

**Comment by jfouyang** [comment]
ShinyCell uses the python package `anndata` to read h5ad files and it seems to me that recent updates to anndata might be responsible for the error. Is it possible to run the following code in R so I can get your anndata version:

```
# Please run this in R and not Python
library(reticulate)
ad <- import("anndata", convert = FALSE)
ad[["__version__"]]
```

And I will investigate this error further in the meantime.

**Comment by CynAro** [comment]
> library(reticulate)
> ad <- import("anndata", convert = FALSE)
> ad[["__version__"]]
0.7.6

**Comment by CynAro** [comment]
@jfouyang I reinstalled ShinyCell and now it is working beautifully. Thank you!

**Comment by jfouyang** [comment]
Hi! Glad that it is working well now. 

Just to share, I was using anndata v0.7.5 previously and it actually threw up some errors. But you should not get any errors now if you are running the latest anndata v0.7.6. 

Also, as you pointed out, if you are running it on the example file `endocrinogenesis_day15.h5ad`,  you will get a warning
```
FutureWarning: Moving element from .uns['neighbors']['distances'] to .obsp['distances'].
This is where adjacency matrices should go now.
```
This is because the h5ad file was made from an older version of scanpy/anndata and they have shifted the location of the k-nearest neighbour distance. However, this piece of information is not required by ShinyCell for visualisation so you can safely ignore the warning.

**Comment by fangpingmu** [comment]
I still get this error when I am using anndata 0.7.6 and ShinyCell 2.1.0.

> makeShinyApp(inpFile, scConf,
+              default.gene1 = "Pcsk2", default.gene2 = "Dcdc2a",
+              default.multigene = c("Pcsk2", "Dcdc2a", "Ank", "Gng12", "Top2a",
+                                    "Pak3", "Tmem163", "Nfib", "Pim2", "Smoc1"),
+              shiny.dir = "shinyAppH5ad/",
+              shiny.title = "ShinyCell h5ad Example")
/ihome/crc/install/anndata/0.7.6/python3.8/lib/python3.8/site-packages/anndata/compat/__init__.py:180: FutureWarning: Moving element from .uns['neighbors']['distances'] to .obsp['distances'].

This is where adjacency matrices should go now.
  warn(
/ihome/crc/install/anndata/0.7.6/python3.8/lib/python3.8/site-packages/anndata/compat/__init__.py:180: FutureWarning: Moving element from .uns['neighbors']['connectivities'] to .obsp['connectivities'].

This is where adjacency matrices should go now.
  warn(
Error in match(x, table, nomatch = 0L) :
  'match' requires vector arguments

> library(reticulate)
> ad <- import("anndata", convert = FALSE)
> ad[["__version__"]]
0.7.6
