### ISSUE TITLE
Disabling "Toggle to subset cells" in the app

### ISSUE THREAD

**Issue by dKlee99** [SGDDNB/ShinyCell#15]
Hi,
Our lab is planning to use your package to create a database to be published soon and there are some functions in the app that we don't really want to make it appear such as "Toggle to subset cells" or "Download PDF/PNG". I would like to know if I should do this by manually changing ui/server script or by functions like "delMeta"/"modMetaName" available to customize options. 

Thank you very much for providing this wonderful package!

**Comment by jfouyang** [comment]
Hi, to remove the "Toggle to subset cells", you will have to edit both the `ui.R` and `server.R` scripts manually for now.
First, in `server.R`, you need to replace all instance of `inpConf[UI == inpsub1]$ID` with `inpConf$ID[1]`. This will deactivate the subsetting of cells on the plots.
Second, in `ui.R`, you need to comment out all the UI blocks related to the subsetting of cells. To do so, search for the phrase `Toggle to subset cells`. Then comment out the whole block of UI code related to it. An example is shown below where the line with `# column( ` to the line with `# ), # End of column (6 space) `. This then has to be repeated for all the UI blocks to the subsetting of cells (of which there should be 4 of them).

I am afraid that this is the only way to remove the "Toggle to subset cells" function at this point in time.

```
            12, selectInput("sc1a1drX", "X-axis:", choices = sc1conf[dimred == TRUE]$UI, 
                           selected = sc1def$dimred[1]), 
            selectInput("sc1a1drY", "Y-axis:", choices = sc1conf[dimred == TRUE]$UI, 
                        selected = sc1def$dimred[2])) 
        ) 
      ), # End of column (6 space) 
      # column( 
      #   3, actionButton("sc1a1togL", "Toggle to subset cells"), 
      #   conditionalPanel( 
      #     condition = "input.sc1a1togL % 2 == 1", 
      #     selectInput("sc1a1sub1", "Cell information to subset:", 
      #                 choices = sc1conf[grp == TRUE]$UI, 
      #                 selected = sc1def$grp1), 
      #     uiOutput("sc1a1sub1.ui") 
      #   ) 
      # ), # End of column (6 space) 
      column( 
        6, actionButton("sc1a1tog0", "Toggle graphics controls"), 
        conditionalPanel( 
          condition = "input.sc1a1tog0 % 2 == 1", 
          fluidRow( 
            column( 
```

**Comment by jfouyang** [comment]
Regarding the removal of "Download PDF/PNG" functionality, I strongly advise against it. Being able to export the images in your shiny app would likely boost the number of citations that your work will recieve. Furthermore, even if this image exporting function is being removed, users of the shinyapp can still get images of your plots by taking screenshots or right-clicking on the plots to save images.

**Comment by dKlee99** [comment]
Thank you very much for your comment, it worked! 
Regarding "Download PDF/PNG" functionality, I agree to your comment. 
Should I apply the same method to disable other "Toggle graphics controls"/"Toggle plot controls"?

**Comment by jfouyang** [comment]
Hi,

For `Toggle graphics controls`, it is used to control the aesthetics of the plot like the point size etc. And for `Toggle plot controls`, it is used to change the colour scheme for continuous data e.g. gene expression. So there is no harm in keeping these buttons as they help to finetune the appearance of your plots. We added these functionalities to make it easier to browse on a variety of devices, for example, you might want a smaller plot size or font size if you are browsing the app on your mobile and bigger sizes if you are browsing on a desktop.

As for the dimension reduction, if you only ran UMAP, the shinycell app should only contain UMAP and PCA coordinates as plotting options. I don't see why you would want to hide the PCA coordinates and most people would not be interested in the PCA anyways.

**Comment by jfouyang** [comment]
The dimensional reduction code is very well integrated into the ShinyCell package, appearing at numerous locations throughout the code. Thus, it is not practical to comment out code related to it. The best solution I have is to remove the PCA and harmony coordinates in the Seurat object before running ShinyCell. This will prevent the PC / harmony1 coordinates from appearing.

To do so, you can run the following to modify your seurat object before running ShinyCell:
```
Reductions(seu)           # This gets you the names of the dimensional reduction 
seu[["pca"]] = NULL       # Removes PCA coordinates
seu[["harmony"]] = NULL   # make sure this name matches the one shown by Reductions(seu) 
```

**Comment by dKlee99** [comment]
Thank you so much for your help!!

**Comment by jfouyang** [comment]
Hi, in the latest update of ShinyCell, there is now a new argument `enableSubset` in the `makeShinyApp` or `makeShinyCodesMulti` function. If you want to disable the "Toggle to subset cells", you can set `enableSubset = FALSE` to deactivate the functionality. Do try it out!
