### ISSUE TITLE
sce colnames missing: Error in `[.data.table`(sc1meta, , c("sampleID", as.character(sc1conf$ID)) column(s) not found: sampleID

### ISSUE THREAD

**Issue by NadineBestard** [SGDDNB/ShinyCell#17]
The issue #12 solved that the lack of colnames in the dimensional reduction causing errors in the app.
The lack of column names in the sce ( the cell names) also causes problems.
This hapens if the cell names of the single cell object are not defined ( the default for DropletUtils::read10xCounts)
```
> colnames(sce)
NULL
```
 This is an issue that also caused the as.Seurat function to fail, as seen [here](https://support.bioconductor.org/p/9136786/) and [here](https://github.com/satijalab/seurat/issues/830).
The error that comes up in this case is:
`Error in `[.data.table`(sc1meta, , c("sampleID", as.character(sc1conf$ID)) column(s) not found: sampleID`

**Comment by jfouyang** [comment]
Can I clarify one thing? Which function gave the error message? Is it `createConfig()` or `makeShinyApp()`? It would be really helpful to know the exact function so as to speed up the troubleshooting process.

**Comment by jfouyang** [comment]
Can I clarify one thing? Which function gave the error message? Is it `createConfig()` or `makeShinyApp()`? It would be really helpful to know the exact function so as to speed up the troubleshooting process.

**Comment by jfouyang** [comment]
Hi, first of all, apologies for the late reply. It has been a crazily hectic week for me.

I just checked and the absence of colnames in a SCE object does cause ShinyCell not to work propely. To circumvent that, I added an additional check to check if the colnames are present. And if they are not, the colnames will be populated with "cell_X" labels. I tested it on my end and everything works now.

**Comment by NadineBestard** [comment]
Hi, 
Don't worry, as I could detect from where the issue was comming from, it was easy to modify my object to add colnames and this was not holding me back! I just thought you would like to be aware of the problem and add something in your code like you did, to make it more robust to this is a comon situation for sce objects.
Many thanks for keeping improving this package!
