### ISSUE TITLE
Changing default point size 

### ISSUE THREAD

**Issue by dKlee99** [SGDDNB/ShinyCell#18]
Hi,

our data has 200k cells and the default point size (in Toggle graphics control) '1' was not suitable for visualization. Is there an option to change the default point size to '0.25'? Always appreciate your help!

**Comment by jfouyang** [comment]
You can change the default point size by modifying the `ui.R` file. Search for the keywords "Point size" and you will see code looking like this:

```
6, sliderInput("sc1a1siz", "Point size:", 
               min = 0, max = 4, value = 1.25, step = 0.25), 
```

You can then change the value from `value = 1.25` to `value = 0.25` to change the default point size. You will need to do this five times per dataset as the size of the data points can be altered in five different tabs, namely the first three side-by-side visualdation tabs, the co-expression tab and the violin/boxplot tab.

**Comment by dKlee99** [comment]
It worked, I appreciate your help!

**Comment by jfouyang** [comment]
Hi, in the latest update of ShinyCell, there is now a new argument `defPtSiz` in the `makeShinyApp` and `makeShinyCodesMulti` function to allow users to modify the default point size. Do try it out!

**Comment by dKlee99** [comment]
Great, thank you very much!
