### ISSUE TITLE
Gene expression not showing for some genes in bubbleplot/heatmap

### ISSUE THREAD

**Issue by GBeattie** [SGDDNB/ShinyCell#20]
Hey,

Really like this app! One thing I've noticed a few times is certain genes which don't plot on bubblemap/heatmap. Below is an example of the bubble plot, you can see the problem gene is hbz(6of8) (this is a killifish experiment, hence the strange annotations). Note, it will only work with cluster rows turned off (Error occurs otherwise).

![image](https://user-images.githubusercontent.com/11555832/125084461-7a4b5780-e0c1-11eb-9919-7e586133c381.png)

Checking this gene on the corresponding UMAP shows it's robustly expressed at high levels in one of the clusters.

![image](https://user-images.githubusercontent.com/11555832/125084732-c3031080-e0c1-11eb-9c1b-38a0073fd016.png)

Let me know if I can provide any more information, any assistance greatly appreciated! 
All the best,
Gordon

**Comment by jfouyang** [comment]
Hi, it seems to me that the parenthesis are not the ones giving the problems. 

If I may ask, did you normalise the gene expression using SCTransform?

**Comment by GBeattie** [comment]
I've managed to fix it, my fault, I did run SCTransform but then switched to the RNA assay before creating the shiny and didn't normalise the assay, so the expression of that gene is in counts in the plot above!

I normalised and re-generated the shiny and that has fixed it, not sure why but I'll close this. Thanks!

**Comment by jfouyang** [comment]
I think the bubbleplot "crashes" when the gene expression values are too big. This is because the gene expression is being z-transformed / scaled and this transformation fails for big numbers.
