### ISSUE TITLE
Adding Pseudotime/Trajectories plots ?

### ISSUE THREAD

**Issue by lorbaer** [SGDDNB/ShinyCell#21]
Hi John,
found this project today, got it running and I'm amazed. :)

Guess I will switch from my own build quite basic python dash app to your shiny app. However I would like to know about adding pseudotime/trajcetorie plots generated from slingshot ( https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-018-4772-0 ). The calculation is quite slow. So far I calculated everything and saved it in an object. This could maybe be added simply in the makeShinyApp?

cheers

**Comment by jfouyang** [comment]
Hi. First of all, many apologies for the late reply. It has been a busy period finishing some projects and taking vacation.

Currently, there is no automated way to include trajectory plots as (i) there are a lot of trajectory inference tools out there and it is impossible to cover them and (ii) inclusion of such plots may slow down the shiny app. That said, in the next reply, I will provide some R code if you are interested to add these trajectory plots manually into the R scripts.

As for the inclusion of pseudotime, you can add that as a metadata column into the sce/seurat object. Then you will be able to visualise it like other continuous-valued single-cell metadata e.g. no. detected genes.

**Comment by jfouyang** [comment]
If you would like to manually add the trajectory plots, I have prepared some code here.

Inside `ui.R`, you need to add the following code to create an interface for u to change settings:
```
             div(style="display:inline-block", 
                 numericInput("sc1d1oup.w", "PDF / PNG width:", width = "138px", 
                              min = 4, max = 20, value = 10, step = 0.5)) 
      )  # End of column (6 space) 
    )    # End of fluidRow (4 space) 
  )      # End of tab (2 space) 
   ,    

##### START OF NEW CODE TO ADD #####
### Tab1.x1: New tab for slingshot
tabPanel( 
  HTML("Slingshot Trajectory"), 
  h4("Slingshot trajectory"), 
  "In this tab, users can visualise the Slingshot trajectory.",
  br(),br(), 
  fluidRow( 
    column( 
      3, style="border-right: 2px solid black", 
      selectInput("sc1x1inp1", "Lineage to plot:", 
                  choices = c("1", "2", "3"), 
                  selected = "1")
    ), # End of column (6 space) 
    column(9, plotOutput("sc1x1oup") 
    )  # End of column (6 space) 
  )    # End of fluidRow (4 space) 
),     # End of tab (2 space) 
##### END OF NEW CODE TO ADD #####

br(), 
p("", style = "font-size: 125%;"), 
p(em("This webpage was made using "), a("ShinyCell", 
  href = "https://github.com/SGDDNB/ShinyCell",target="_blank")), 
br(),br(),br(),br(),br() 
))) 
```

Then, in `server.R`, you need to add a new function to plot the trajectory. Here I used the example code from Slingshot:
```
  output$sc1x1oup <- renderPlot({ 
    require(Cairo)
    require(slingshot)
    data("slingshotExample")
    rd <- slingshotExample$rd
    cl <- slingshotExample$cl
    sds <- getLineages(rd, cl, start.clus = input$sc1x1inp1)
    sds <- getCurves(sds)
    
    plot(rd, col = cl, asp = 1)
    lines(sds, type = 'c', lwd = 3)
  }, height = 450, width = 600) 
```

Notice that we defined `sc1x1inp1` in ui.R which is then used as `input$sc1x1inp1` in the function in server.R You can modify this to be say "Lineage1", "Lineage2" etc, allowing you to toggle between lineages.

Hope this crash course into Shiny helps!

**Comment by lorbaer** [comment]
Dear John,
thanks for your reply. I will give it a try in the next weeks. :)

cheers

**Comment by jfouyang** [comment]
Closing the issue to inactivity.
