### ISSUE TITLE
No gene names available in gene Expression plot on reduced dimensions

### ISSUE THREAD

**Issue by synlee** [SGDDNB/ShinyCell#29]
Hi John, 

This has been working great. Thank you for providing this app. Everything works fine except for the cellinfo vs geneExpr plot. 
I was able to plot bubbleplot or heatmap with any genes I named it except for gene expression plot on UMAP plot. Only one gene showed up. Would you help me with this issue? Let me know if you need more information. 
![Screen Shot 2021-11-04 at 10 42 17 AM](https://user-images.githubusercontent.com/29548086/140334558-d1967f1e-7db4-4a85-813b-26e4705cb7f0.png)

Thanks,
Se

**Comment by jfouyang** [comment]
Hi Se,

The dropdown bar for the gene name only shows the first few genes sorted by the number of characters in the gene name. Thus, you are seeing the first few genes with very short names i.e. Ar and C2... You will be able to plot any gene that is present in your dataset by typing in the gene name. The shiny app only shows the first few genes as displaying all the possible gene names will slow down the app greatly and we wanted to avoid that.

Assuming that you are using a Seurat object, running `head(rownames(seu)[order(nchar(rownames(seu)))])` (which sorts the gene names by the number of characters) should get you the same genes that you are seeing in the dropdown bar.

Hope this helps.
John

**Comment by synlee** [comment]
@jfouyang 
Got it! Thank you so much for your help, John.

Best,
Se

**Comment by Parul-Kudtarkar** [comment]
@sel041 , Great App! Instead of having dropdown bar for the gene name show the first few genes sorted by the number of characters in the gene name is it possible to have it display custom gene list. Thanks!
