### ISSUE TITLE
Which R version is required?

### ISSUE THREAD

**Issue by jvelghe** [SGDDNB/ShinyCell#3]
Warning in install.packages :
  package ‘ShinyCell’ is not available (for R version 3.6.3)

I have all the dependancies, which R version should I use?

Thanks!

**Comment by jfouyang** [comment]
Hi, ShinyCell should work for any R version > 3.5.

Currently, you can only install ShinyCell via github using the following command:
`devtools::install_github("SGDDNB/ShinyCell")`

`install.packages` is for packages that are deposited on CRAN (for which ShinyCell is not). For additional information on installation, you can further refer to the readme. :)

**Comment by jvelghe** [comment]
Hi John,
Thanks for your prompt response, that's reassuring! I tried downloading it using devtools::install_github("SGDDNB/ShinyCell") a well (devtools already installed). It didn't work yesterday but I think it' because I chose not to update a million things.. works now, thank you! 
Disclaimer: I'm sing this for a single cell dataset to put online, so I might be posting a few questions this week.. :)

**Comment by jfouyang** [comment]
Glad that all turn out well. I will close this issue for now. 

If you have any further questions on putting ShinyCell apps online, I will be glad to take them. There is also a short writeup on the different options to put ShinyCell apps online: https://htmlpreview.github.io/?https://github.com/SGDDNB/ShinyCell/blob/master/docs/4cloud.html

Thanks again for using ShinyCell.
