### ISSUE TITLE
Alternative sheet styling?

### ISSUE THREAD

**Issue by kmshort** [SGDDNB/ShinyCell#32]
Hi,
While the aesthetics can be changed within the plots, I can see no way of changing the global sheet styling. For example, to change the white background to black, flip the black text to white.. How would one go about this?
Use bslib theming or other, as in: https://shiny.rstudio.com/articles/themes.html ?
Could we just insert example code from there into the generated ui.R somewhere? If so, where? 

Or, is there a way within R to add the bslib theming code so when ShinyCell::makeShinyFiles() is run, it inserts that custom code?

**Comment by kmshort** [comment]
I've tried hand editing the ui.R which shinyCell generates to slot in a theme from the "bslib" package. But it's not working.

Here, I tried adding it to the first navbarPage function, as `theme = bs_theme(bootswatch = "minty")`
but the page doesn't implement it. I also tried it after the inital `shinyUI(fluidPage(theme = bs_theme(bootswatch = "minty"),` but that didn't work either.

```
library(shiny) 
library(shinyhelper) 
library(data.table) 
library(Matrix) 
library(DT) 
library(magrittr)
library(bslib)
sc1conf = readRDS("sc1conf.rds")
sc1def  = readRDS("sc1def.rds")

sc2conf = readRDS("sc2conf.rds")
sc2def  = readRDS("sc2def.rds")


### Start server code 
shinyUI(fluidPage( 
### HTML formatting of error messages 
tags$head(tags$style(HTML(".shiny-output-error-validation {color: red; font-weight: bold;}"))), 
list(tags$style(HTML(".navbar-default .navbar-nav { font-weight: bold; font-size: 16px; }"))), 
 
   
### Page title 
titlePanel("The effect of maternal low protein diet on developing kidney gene expression"),  
navbarPage(theme = bs_theme(bootswatch = "minty"),
NULL,  
 navbarMenu("E14.5 LPD/NPD kidneys",### Tab1.a1: cellInfo vs geneExpr on dimRed 
  tabPanel( 
    HTML("CellInfo vs GeneExpr"), 
    h4("Cell information vs gene expression on reduced dimensions"), 
    "In this tab, users can visualise both cell information and gene ",  
    "expression side-by-side on low-dimensional representions.", 
    br(),br(), 
    fluidRow( 
```

**Comment by kmshort** [comment]
Okay,
If I go to bootswatch, save a theme from there, e.g. "Quartz" (because it looks obvious when it is applied) as a css, then put said CSS in
app/ui.R
app/server.R
app/www/Quartz.css

and reference Quartz.css in the ui.R that ShinyCell generates, it almost works.. but makes the header bar huge.

![image](https://user-images.githubusercontent.com/7980275/144772711-551d2753-9122-46f4-8a13-a18c31f03554.png)

It'd be nice to use the bs_theme(bootswatch = "Quartz") <althougth bs_theme doesn't currently support quartz.. so insert any other theme here> just work. But if not, stop the rather oversized bar at the top of the page, and get the font sizes correct.

**Comment by OwenRackham** [comment]
Hello. I am glad that you are finding ShinyCell a useful tool. Your request to add in the style sheet is an excellent one, however, this is not really an issue with the current version of the software but a feature request. There are many such features that we would like to add and we are always compiling a list and we would welcome someone like yourself to add this to the repo if you get it to work. For now, we will close this as an issue. All the best.

**Comment by kmshort** [comment]
whoa whoa Owen, not really finished here, if you may!

Where is the current styling placed in the ui.R? I think it seems sprinkled throughout. Can you tell me where that is implemented and applied in ShinyCell, and how I might be able to modify it? At the moment, however it is applied, the code ShinyCell generates seems to block the application of bs_theme to the output.

**Comment by royfrancis** [comment]
One option is to use `shinythemes` package. For example, you can modify your `ui.R` like so;

```
library(shinythemes)
fluidPage( theme=shinytheme("flatly"))
```
