### ISSUE TITLE
Adjusting the colors for the scale of the UMAP

### ISSUE THREAD

**Issue by shamsbhuiyan** [SGDDNB/ShinyCell#35]
I would like to change the scale on the UMAPs that appear in ShinyCell, both in terms of the color of the scale and the minimum/maximum of the scale. Whats the best way to do this?

Thanks!

**Comment by jfouyang** [comment]
Hi shamsbhuiyan,

There is currently no direct support for custom color palettes for the plots. If you want to modify the color itself, you will have to modify the code directly.

If you look into the first portion of `server.R`, you will see this chunk of code:
```
cList = list(c("grey85","#FFF7EC","#FEE8C8","#FDD49E","#FDBB84", 
               "#FC8D59","#EF6548","#D7301F","#B30000","#7F0000"), 
             c("#4575B4","#74ADD1","#ABD9E9","#E0F3F8","#FFFFBF", 
               "#FEE090","#FDAE61","#F46D43","#D73027")[c(1,1:9,9)], 
             c("#FDE725","#AADC32","#5DC863","#27AD81","#21908C", 
               "#2C728E","#3B528B","#472D7B","#440154")) 
names(cList) = c("White-Red", "Blue-Yellow-Red", "Yellow-Green-Purple") 
```

Basically, `cList` specifies the colours to be used in `scale_color_gradientn` by ggplot2 to specify the color palette. For example, `c("#FDE725","#AADC32",...,"#440154")` specifies the "Yellow-Green-Purple" palette. Thus you can modify `cList` to change color palette.

Hope this helps.

**Comment by shamsbhuiyan** [comment]
Thanks! This worked great!
