### ISSUE TITLE
Keep / remove tabs selectively

### ISSUE THREAD

**Issue by royfrancis** [SGDDNB/ShinyCell#37]
Is there a way to specify which tabs to keep/remove in the config file? For example, removing the **GeneExpr vs GeneExpr** tab.

**Comment by jfouyang** [comment]
Hi Roy,

There is no way to specify what tabs to keep or remove in the config file as we find all the visualizations useful and the purpose of the platform is to encourage easy sharing and browsing of single-cell data.

You may choose to remove it manually by commenting out the code in `ui.R`.

**Comment by royfrancis** [comment]
I eventually realised this as I went through the code. Thanks!
