### ISSUE TITLE
How to supply gene.mapping vector in makeShinyFiles?

### ISSUE THREAD

**Issue by jvelghe** [SGDDNB/ShinyCell#4]
I ran this: 
```
makeShinyFiles(seu, scConf1, gex.assay = "SCT", gex.slot = "data",
                gene.mapping = TRUE, 
                shiny.prefix = "sc1",
                shiny.dir = "shinyAppMulti/",
                default.gene1 = "INS", default.gene2 = "GCG",
                default.multigene = c("INS","GCG","SST","PPY","NPAS4"),
                default.dimred = c("UMAP_1", "UMAP_2"))
```
And got this warning message:
```
Warning message:
In makeShinyFiles(seu, scConf1, gex.assay = "SCT", gex.slot = "data",  :
  Variable genes not found! Did you use specify the wrong assay or wrong seurat object?
```
It doesn't seem like the makeShinyFiles function is finding my gene expression matrix in the Seurat object. I saw when looking into the makeShinyFiles function that "Alternatively, users can supply a named vector where names(gene.mapping) correspond to the actual gene identifiers in the gene expression matrix and gene.mapping correspond to new identifiers to map to." I have attempted to do this below:
```
data <- as(as.matrix(GetAssayData(seu, assay = "SCT", slot = "data")), 'sparseMatrix')
gene.mapping <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
```
I am wondering how to best make the vector, how to reference it in the makeShinyFiles function, and/or what to save it as in the shinyAppMulti directory so it'll be properly utilized in the app. 

Edit: I get the same warning for either my SCT or RNA assays in the data slots, as well as when I set gene.mapping = FALSE. Currently trying other slots, any reason it might not be finding variable genes, and how I can solve this? 

Thank you!

**Comment by jvelghe** [comment]
Nevermind, the warning seemed to not be an issue at all. The app looks AWESOME, probably the best package I've used wow. Thank you for making this!
-Jane

**Comment by jfouyang** [comment]
Hi Jane, yes it's a warning so the shiny app will still be generated. Just to explain a bit further, if the input is a Seurat Object, it will look for highly variable genes calculated by Seurat and set those genes as default genes to be plotted. If it cannot find the highly variable genes, then you get this warning. I just made a small tweak to the code to improve the process of finding highly variable genes so hopefully this warning doesn't appear next time. That said, just to emphasize again, this is just a warning so the shiny app will still be generated.



Regarding the gene mapping (which is unrelated to the above warning), you can set custom gene name mapping. For example, you can create gene mapping like this: 

```
geneMap = c("NANOG", "POU5F1")
names(geneMap) = c("ENSG00000111704", "ENSG00000204531")
```

and it will convert the ensembl gene IDs ENSG00000111704, ENSG00000204531 to NANOG and POU5F1 respectively. It is mainly useful if your gene expression is in ensembl IDs and you want to convert them to more user-friendly/readable gene names. So don't worry about this if your data is already using gene names.
