### ISSUE TITLE
Warning: Error in setnames: Can't assign 3 names to a 5 column data.table

### ISSUE THREAD

**Issue by shamsbhuiyan** [SGDDNB/ShinyCell#43]
Hi, I am trying to display the UMAP Seurat object in ShinyCell, but I get this error: 
![image](https://user-images.githubusercontent.com/12201113/158209127-7c6943c5-b388-4fc2-a8a3-b0ab347e8c90.png)

However, the tSNE plot shows up. When I run `DimPlot()` on the object in R, the UMAP does display so I believe that the reductions are present in the object. Here is the output for the reductions slot of the seurat object:
```
$pca
A dimensional reduction object with key PC_ 
 Number of dimensions: 20 
 Projected dimensional reduction calculated:  FALSE 
 Jackstraw run: FALSE 
 Computed using assay: RNA 

$tsne
A dimensional reduction object with key tSNE_ 
 Number of dimensions: 2 
 Projected dimensional reduction calculated:  FALSE 
 Jackstraw run: FALSE 
 Computed using assay: RNA 

$umap
A dimensional reduction object with key UMAP_ 
 Number of dimensions: 2 
 Projected dimensional reduction calculated:  FALSE 
 Jackstraw run: FALSE 
 Computed using assay: RNA 
```

Any idea how I might fix this?

**Comment by jfouyang** [comment]
Hi, it seems that the UMAP coordinates are "missing" somehow. All the dimension reduction coordinates are stored in the `sc1meta.rds` object in the shiny app folder. Can you help me open the `sc1meta.rds` object in your R/Rstudio and run the commands below to check if the coordinates are present?

```
colnames(sc1meta)[grep("UMAP", colnames(sc1meta), ignore.case = TRUE)]
colnames(sc1meta)[grep("TSNE", colnames(sc1meta), ignore.case = TRUE)]
```

**Comment by shamsbhuiyan** [comment]
Hi, I seem to have figured out a work around! I will go ahead and close to issue. Thanks!

**Comment by luoxungh** [comment]
> Any idea how I might fix this?

I also came across the same problem, and how did you solve the problem?

**Comment by luoxungh** [comment]
> 

I run the code you give, and the results is below
![image](https://user-images.githubusercontent.com/62649650/227506456-b2abf252-a73d-4915-a189-3e46b4af1f7f.png)
There are four columns related to UMAP, which may cause the problem.
