### ISSUE TITLE
error when less genes in the assay

### ISSUE THREAD

**Issue by LinAU** [SGDDNB/ShinyCell#49]
Firstly, Thank you very much for developing this very nice tools for data sharing. 

I have tried with my genome wide scRNAseq data, which with around 20k genes. It works perfectly! 
However, when I worked with my target panel scRNAseq data, which is with 438 genes in RNA assay, the error showed up. 

Here it is my code:
makeShinyApp(seu_slim, scConf, gene.mapping = F, shiny.title = "Database") 

Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  index larger than maximal 438

may I ask what should I do to make it work? Thanks in advance for your help

KR,
Lin

**Comment by jfouyang** [comment]
Hi @LinAU,

I did an investigation and realized that this error occurs when there are less than 500 genes in your Seurat object. What happened is that, for efficiency reasons, ShinyCell works in chunks of 500 genes when preparing the files for the shiny app. Thus, the code misbehaves when there are less than 500 genes. I have edited the code to lower the chunkSize when there are less than 500 genes. Can you try installing the newest version of ShinyCell and try again?

**Comment by jfouyang** [comment]
Hi @LinAU, 

Glad that it works! Also, I have modified the ShinyCell code accordingly. So you should no longer get any error if you install the latest version of ShinyCell.
