### ISSUE TITLE
Error while importing h5ad file 

### ISSUE THREAD

**Issue by CynAro** [SGDDNB/ShinyCell#5]
Hi,
I'm trying to import my h5ad file to run Shinycell. I've installed all the packages mentioned. 
library(ShinyCell)
getExampleData("h5ad")
inpFile = "macaque_integrated_neuronsv2.h5ad"
scConf = createConfig(inpFile)
makeShinyApp(inpFile, scConf, 
             default.gene1 = "A1BG", default.gene2 = "A1CF",
             default.multigene = c("A1BG", "A1BG-AS1", "ATCF"),
             shiny.dir = "ShinyCell/", 
             shiny.title = "Shiny Cell sequencing") 

I get the following error. 
Error in py_module_import(module, convert = convert) : 
  ImportError: /ihome/rseal/cma83/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/h5py/defs.cpython-36m-x86_64-linux-gnu.so: undefined symbol: H5Dget_num_chunks

**Comment by jfouyang** [comment]
Hi, it seems like it is an error associated with the python package `anndata`, which is a dependency of ShinyCell.

Can you run the following code on R and see if the package is working?
```
library(reticulate)
ad <- import("anndata", convert = FALSE)
```

Also, can you reinstall the package in R and try running it again?
`reticulate::py_install("anndata")`

And finally, can I ask what operating system are you running ShinyCell on? macOS? or Linux Ubuntu?

**Comment by CynAro** [comment]
**library(reticulate)
ad <- import("anndata", convert = FALSE)**

The same error as before appears after running this. I tried reinstalling and that did not work either. 
I have Windows but I am using the institution's cluster to run the program.

**Comment by jfouyang** [comment]
This is a really unusual error and I should emphasize that it is an error with the `anndata` python package and not with ShinyCell. You could raise this as an issue at `anndata`'s github page (https://github.com/theislab/anndata) and see if the authors of `anndata` can help.

And to clarify further, for the machine where the code is being run i.e. the institution's cluster, is the operating system Linux? If possible, can you run `sessionInfo()` on R and paste the output here?

Also, can I ask if you have performed any single-cell analysis using the `scanpy` pipeline on this same machine? I asked because you would required `anndata` to work for things to run. If so, has anything changed since you ran the `scanpy` pipeline.

**Comment by jfouyang** [comment]
Closing this issue due to long inactivity.

**Comment by Parul-Kudtarkar** [comment]
trim

@jfouyang thank you for creating a user-friendly tool. Regarding loading h5ad files, I get same error. 
```
Loading required package: readr
Loading required package: RColorBrewer
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'anndata'
Calls: runApp ... ..stacktraceon.. -> createConfig -> import -> py_module_import
Execution halted'
```

anndata is installed 
```
library(reticulate)
ad <- import("anndata", convert = FALSE)
```
gives no error.

Here is output of sessionInfo()
> sessionInfo()
```
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.1
```

**Comment by Parul-Kudtarkar** [comment]
PS. anndata version is 0.8.0
