### ISSUE TITLE
export legend

### ISSUE THREAD

**Issue by mdidish** [SGDDNB/ShinyCell#6]
Hello
First of all, thank you very much for this application which is very useful for sharing information between bioinformatics and biologist!

I just discovered the Coexpression Gene tab. Is it possible to modify the png / pdf export to include the legend information? Otherwise we will use the screen print.

Thank you
Marc

**Comment by jfouyang** [comment]
Hi Marc, glad that you like the tool! :)

There are two buttons below the legend (circled red in the screenshot below) that allow you to export the legend either as a PDF or PNG (similar to the main plot). So you have to export the plot and the legend separately as two images. Hope this helps! 

![Screenshot 2021-03-18 at 1 08 50 AM](https://user-images.githubusercontent.com/29743749/111508370-992a8480-8786-11eb-91a0-4b6394dc3e29.png)

**Comment by mdidish** [comment]
oups sorry I hadn't seen these buttons!
Thanks again for all your tutorials.
Marc
