### ISSUE TITLE
Subsetting cells by multiple (different) annotation columns

### ISSUE THREAD

**Issue by vkartha** [SGDDNB/ShinyCell#70]
Nice package! I noticed when you try to toggle subsetting cells for a given tab, you can only subset by a single field, and not more than 1 field (i.e. the chosen values aren't saved for a different round of filtering when switching to a different field, it starts fresh everytime you choose a new field to filter on). Wondering if you have a workaround for this so that for that same tab, you can subset on multiple fields (this would just be an '&' logical for the combination of options chosen). It would be refreshed if the tab is switched and returned, the way it does currently.

**Comment by jfouyang** [comment]
Hi, we do have users who have requested this feature but it is cumbersome to implement in our experience and quickly becomes a slippery slope with users wanting to subset by 2 or 3 or 4 fields etc.

The easiest way to circumvent this is to create a new field concatenating two fields. For example, you have a `patient` field and a `diseased/control` field. You can make a new field called `patient_diseased` which will have all the combinations you need.
