### ISSUE TITLE
Feature request: interactive plots

### ISSUE THREAD

**Issue by vkartha** [SGDDNB/ShinyCell#71]
I think if you can pass your ggplots (mainly the UMAPs) to plotly's ggplotly() function, you should seamlessly get an interactive version (perhaps minor aesthetic tweaks need to be made) that will then allow users to interactively alter plots (zoom, hover with text highlights etc.) , which can be nice for exploration.

**Comment by jfouyang** [comment]
Hi, this has been a common request but we decided not to implement it so that the app can render all the images quickly. ShinyCell has been tested for datasets up to half a million cells: the UMAPs are generated fairly quickly and we do not want to compromise on the speed and ease of usage.
