### ISSUE TITLE
Is it possible to incorporate seurat 5 object in the ShinyCell

### ISSUE THREAD

**Issue by anksi** [SGDDNB/ShinyCell#74]
Hi,
Thanks for the wonderful tool.
I have used it for my previous projects and it indeed was very helpful.
Lately, I have started using Seurat 5 where RNA assay has "data" inside "layer" slot which is not recognised by ShinyCell.

I have tried downgrading seurat object from version 5 to previous versions but I was not successful in converting it.
Do you have any workaround or is there anyone who has faced the same issue before, I will be happy to here about the same.

Thanks in advance!

**Comment by anksi** [comment]
I manage to resolve the issue

**Comment by haukeh90** [comment]
Dear anksi, 

could you please share your workaround here? I have similar problems with creating a shiny app from SeuratV5 assay. Thank you!

best 

Hauke

**Comment by anksi** [comment]
Dear Hauke,

I have added an additional assay in SeuratV5 object to move RNA assay one level up and then it worked out for me.
Let me know if in case you need code for the same.

Cheers
Ankita

**Comment by zpohk** [comment]
I have created a pull request to add support for Seurat v5 objects (after JoinLayers is performed).
https://github.com/SGDDNB/ShinyCell/pull/80

Install with `devtools::install_github("SGDDNB/ShinyCell", ref = remotes::github_pull(80))`

**Comment by olneykimberly** [comment]
@anksi , I would like the code please. It's not working for me. 

> makeShinyApp(obj = shiny.obj,
+              scConf = sc.config, 
+              gene.mapping = TRUE,
+              shiny.title = "Pipseq v3 chemistry single nucleus")
Error in slot(obj@assays[[gex.assay[1]]], gex.slot[1]) : 
  no slot of name "data" for this object of class "Assay5"
