### ISSUE TITLE
Published Github Release?

### ISSUE THREAD

**Issue by MynorKyllJoy** [SGDDNB/ShinyCell#8]
Hello,

thank you for this amazing package.
Would it be possible to have one published Github release of this package?

EDIT:
Sorry, I meant a tagged Github release when I wrote published Github release.

**Comment by jfouyang** [comment]
Do you mean the package version? The version number is updated when the code is updated.

**Comment by MynorKyllJoy** [comment]
No, I actually mean a tag for the current version of the package.
You can use the command 'git tag -a v2.0.0' or 'git tag -a v2.0.0 -m "Tag Message"' to create a tag of the current version of your code.
Then you can push your tagged code with 'git push --tags' in your Github repository.

By tagging your repository, you create a copy of the current code which will not change when you make future changes.
By pushing the tagged copy into Github you enable users to download older versions of the code.
For example, if you were to create a tagged version of v2.0.0 now and later upgrade to v3.0.0, people could choose which version of the code they want to use.
This is beneficial, in case a hypothetic v3.0.0 becomes incompatible with an older version of one of ShinyCells dependencies, e.g. Seurat v3.1, and there are users which still have to use this older version of Seurat because of compatibility issues with other packages they have to use.
You can also delete and change the tags later, i.e., after you fix a bug since changes made after a tagged version was created will not affect the tagged version.

**Comment by jfouyang** [comment]
Hi @MynorKyllJoy

Thanks for explaining github tags! It is really helpful.

As requested, I have tagged the appropriate commits to major and minor versions of ShinyCell. To summarise, there is:
- v1.0 corresponding to the biorxiv preprint
- v1.1 where we added support for all major single-cell formats (Seurat/SCE/loom/h5ad)
- v2.0 corresponding to the bioinformatics publication

Please do use the newest version as we have revamped the package substantially following some helpful comments during the publication review process.
