### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dKlee99** [SGDDNB/ShinyCell#9]
Hi, 
I have found your package very helpful! Thank you very much, 

I have error message as following whilst trying to customize ShinyCell aesthetics:
Cannot find 'ID' in this Seurat object

How should I solve this error??

**Comment by jfouyang** [comment]
Hi~ Glad that you find the package useful for your work.

It would be helpful to provide more details. What function did you run that gave this error?

**Comment by dKlee99** [comment]
I have solved the issue! thank you very much
